server:
  port: 8082

spring:
  application:
    name: auth
  datasource:
    username: 'bgunduz'
    url: jdbc:postgresql://localhost:5432/auth
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
eureka:
  client:
    service-url:
      defaultZone: http://bgunduz:passwd@localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

jwt:
  secret: 9a8fc392dd1a4127d2bc30d6ddb8d205b645fb20f817bb4c9890468c7506300c